Post.create title: "A", content: "Content"
Post.create title: "A", content: "Content"
Post.create title: "A", content: "Content"
Post.create title: "A", content: "Content"
Post.create title: "A", content: "Content"
Post.create title: "A", content: "Content"

User.create email: "kyhuuhai@gmail.com", name: "Bin"
User.create email: "kyhuuhai@gmail.com", name: "Bin"
User.create email: "kyhuuhai@gmail.com", name: "Bin"
User.create email: "kyhuuhai@gmail.com", name: "Bin"
User.create email: "kyhuuhai@gmail.com", name: "Bin"
User.create email: "kyhuuhai@gmail.com", name: "Bin"
User.create email: "kyhuuhai@gmail.com", name: "Bin"